### ISSUE TITLE
Local tdlib database encryption not working

### ISSUE THREAD

**Issue by z8512** [TruncatedDinosour/arigram#10]
I just entered a random password in config file but its not working. Where can I find the actual password required for encryption or what kind of password should I use?

**Comment by z8512** [comment]
2nd Question: I installed arigram using `pip3 install git+https://github.com/TruncatedDinosour/arigram.git` is it okay?

**Comment by ar1ja** [comment]
> 2nd Question: I installed arigram using `pip3 install git+https://github.com/TruncatedDinosour/arigram.git` is it okay?

yeah ig

**Comment by ar1ja** [comment]
> I just entered a random password in config file but its not working. Where can I find the actual password required for encryption or what kind of password should I use?

You can definally use gpg with subprocess, or you can encrypt it yourself using using python,

for example you can use [subprocess](https://docs.python.org/3/library/subprocess.html).check_output() and make
it run some command, or make the user enter something from stdin, like a local password or maybe use something
like [python cryptography](https://pypi.org/project/cryptography/) and implement encryption yourself

and on that, you should reset arigram for the encryption to work as it's not that the database is getting encrypted, it's the
content:

```sh
$ rm -rf ~/.cache/arigram
$ arigram
```

**Comment by ar1ja** [comment]
I misunderstood the question, just do the resetting of database thing:

```sh
$ rm -rf ~/.cache/arigram
$ arigram
```

You will have to re-log-in, but **keep the config** so it can encrypt it, you can use any password as
long as it's is valid python (like you should not do `"""`)

**Comment by z8512** [comment]
Thank  you working now
