### ISSUE TITLE
Can I use this repo to export public channal chats?

### ISSUE THREAD

**Issue by zydjohnHotmail** [TruncatedDinosour/arigram#13]
Hello:
I have joined about 30 public channels, I want to export 2 of them, the channel chats every day.
I am using Windows 10, and Telegram desktop version 4.0.1, I can export channel chats by hand from Telegram desktop by setting 6 different parameters.
However, this type of job is tedious, I want to know if I can use this repo to make channel chats exporting job as a Python script, so I can call the Python script later on, I don't have to do the job by hand every day.
Please advise,
Thanks,

**Comment by ar1ja** [comment]
You can move up every message using `ctrl.next_msg()` and then get
the content using `ctrl.model.get_current_message_text()` and then append it to some
file

`ctrl` should the the first argument of your function:

```py
from arigram.controllers import msg_handler


def export_msgs(ctrl) -> None:
    ...


CUSTOM_KEYBINDS = {"X": {"func": export_msgs, "handler": msg_handler}}
```

All implementations of these functions are in `arigram/controllers.py`, the `Controller` class

**Comment by ar1ja** [comment]
Also, this project is quite dead right now, I might work on it
some time again but as long as it works I'm probably going to rarely push
anything to the repo

**Comment by zydjohnHotmail** [comment]
OK, thanks!
