### ISSUE TITLE
window

### ISSUE THREAD

**Issue by OmiChrome** [TruncatedDinosour/arigram#16]
hey can u make it possible for window 

such as on powershell . with arigram.exe 
also with scoop-package installtion :D

**Comment by ar1ja** [comment]
sorry but nope, I am more of a UNIX person and
I got no expierience in NT stuffs, MacOS and Linux are
already supported and probably BSD, if you want, this is FOSS
software so you are very free to fork it and port it :D

But sorry, I cannot, have a nice resr of your day <3

**Comment by OmiChrome** [comment]
:( okay thx
