### ISSUE TITLE
TODO: Sponsored messages support

### ISSUE THREAD

**Issue by ar1ja** [TruncatedDinosour/arigram#2]
Telegram has dropped support for forks with no sponsored messages support

```
Traceback (most recent call last):
  File "/home/ari/.local/bin/arigram", line 8, in <module>
    sys.exit(main())
  File "/home/ari/.local/lib/python3.9/site-packages/arigram/__main__.py", line 72, in main
    tg.login()
  File "/home/ari/.local/lib/python3.9/site-packages/telegram/client.py", line 574, in login
    self.authorization_state = self._wait_authorization_result(result)
  File "/home/ari/.local/lib/python3.9/site-packages/telegram/client.py", line 504, in _wait_authorization_result
    result.wait(raise_exc=True)
  File "/home/ari/.local/lib/python3.9/site-packages/telegram/utils.py", line 45, in wait
    raise RuntimeError(f'Telegram error: {self.error_info}')
RuntimeError: Telegram error: {'@type': 'error', 'code': 406, 'message': 'UPDATE_APP_TO_LOGIN', '@extra': {'request_id': 'updateAuthorizationState'}}
```

So have to make a TODO, refer to https://core.telegram.org/api/layers#layer-132

**Comment by ar1ja** [comment]
I guess a python-telegram update to 0.15.0 was enough lol

**Comment by pannet1** [comment]
> I guess a python-telegram update to 0.15.0 was enough lol

how to update python-telegram to 0.15
mine is 0.14

**Comment by ar1ja** [comment]
> > I guess a python-telegram update to 0.15.0 was enough lol
> 
> how to update python-telegram to 0.15 mine is 0.14

You have to edit the source itself, or try this fork until paul updates to python-telegram 0.15.0

if you still want tg:

- remove tg
- Bump the python-telegram dependency in pyproject.toml and setup.py to `>=0.15.0`
- If you get any `KeyError`s try fixing them, for example if you get an error for `invite_link` as far as I'm aware it doesn't exist anymore so you will have to remove it, or debug the source, still refactoring this fork for this huge change
- reinstall tg **from source** (aka. not from aur, from your edited source)
