### ISSUE TITLE
Keep sensitive information out of conf.py

### ISSUE THREAD

**Issue by hejops** [TruncatedDinosour/arigram#20]
In order to make `conf.py` more portable across systems (e.g. via git repos), sensitive information such as `PHONE`, `ENC_KEY`, etc should be stored in a separate file.

**Comment by ar1ja** [comment]
yes obv

```py
with open(
    os.path.expanduser("~/Ari/passwd/phone_number.n"), "r", encoding="utf-8"
) as pn:
    PHONE = pn.readline().strip()
```

this is why code as config is so nice, this is what i do

thanks for the concern though

**Comment by hejops** [comment]
Oh yeah, good point, didn't cross my mind at all. Thanks for reminding me!
