### ISSUE TITLE
Notifications 

### ISSUE THREAD

**Issue by d13g0x** [TruncatedDinosour/arigram#3]
Hello, I would like you to better explain part of the configuration of the notifications. I would like to have them running, I am currently using Dunst in Archlinux.

Your fork is very good, but I only wanted to be able to have the notifications so that it is perfect.

thank you. :)

**Comment by ar1ja** [comment]
Hi. sorry for taking a while to reply :)

In config you need to define `NOTIFY_FUNCTION` with a function that you want to be called on every notification, arguments will be passed to it as notification params :)

for example in my config I have:

```py
from arigram import config as tg_config
from simpleaudio import WaveObject
from threading import Thread
from plyer import notification


class Custom:
    def _play_wav(self, wave_path: str) -> Thread:
        def player() -> None:
            wave_obj = WaveObject.from_wave_file(wave_path)
            play_obj = wave_obj.play()
            play_obj.wait_done()

        sound = Thread(target=player)
        sound.setDaemon(True)

        return sound

    def _notify(self, title: str, message: str) -> Thread:
        def notifier() -> None:
            if notification.notify is not None:
                notification.notify(
                    app_name=f"arigram {arigram.__version__}",
                    title=title,
                    message=message,
                )

        notif = Thread(target=notifier)
        notif.setDaemon(True)

        return notif

    def notify(self, *args, **kwargs) -> None:
        del args

        self._notify(str(kwargs.get("title")), str(kwargs.get("msg"))).start()
        self._play_wav(f"{tg_config.CONFIG_DIR}resources/notification.wav").start()


custom_code = Custom()
NOTIFY_FUNCTION = custom_code.notify
```

the _... functions are just helpers, they self-expain i think, `_pay_wav()` just pays a wav file in a seperate thread and `_notify()` notifies you from a different thread and makes them daemonic (just makes them background) so not to make the application wait.

the notify function just takes arguments from **kwargs and just ignore *args, in kwargs you get the info passed as kwargs, for example icon, message text, etc. (see [this](https://github.com/TruncatedDinosour/arigram/blob/3f768ff00f26596ce60d7d86e7aa3e5dcfe35fb1/arigram/utils.py#L201) to see what gets passed) and converts them to string just in case something turns out to be `None` and them it just notifies the user using plyer and plays the [wav file](https://github.com/TruncatedDinosour/dotfiles-cleaned/raw/gentoo/dotfiles/config/arigram/resources/notification.wav) which is just the default telegram notification sound :)

**Comment by d13g0x** [comment]
> Hi. sorry for taking a while to reply :)
> 
> In config you need to define `NOTIFY_FUNCTION` with a function that you want to be called on every notification, arguments will be passed to it as notification params :)
> 
> for example in my config I have:
> 
> ```python
> from arigram import config as tg_config
> from simpleaudio import WaveObject
> from threading import Thread
> from plyer import notification
> 
> 
> class Custom:
>     def _play_wav(self, wave_path: str) -> Thread:
>         def player() -> None:
>             wave_obj = WaveObject.from_wave_file(wave_path)
>             play_obj = wave_obj.play()
>             play_obj.wait_done()
> 
>         sound = Thread(target=player)
>         sound.setDaemon(True)
> 
>         return sound
> 
>     def _notify(self, title: str, message: str) -> Thread:
>         def notifier() -> None:
>             if notification.notify is not None:
>                 notification.notify(
>                     app_name=f"arigram {arigram.__version__}",
>                     title=title,
>                     message=message,
>                 )
> 
>         notif = Thread(target=notifier)
>         notif.setDaemon(True)
> 
>         return notif
> 
>     def notify(self, *args, **kwargs) -> None:
>         del args
> 
>         self._notify(str(kwargs.get("title")), str(kwargs.get("msg"))).start()
>         self._play_wav(f"{tg_config.CONFIG_DIR}resources/notification.wav").start()
> 
> 
> custom_code = Custom()
> NOTIFY_FUNCTION = custom_code.notify
> ```
> 
> the _... functions are just helpers, they self-expain i think, `_pay_wav()` just pays a wav file in a seperate thread and `_notify()` notifies you from a different thread and makes them daemonic (just makes them background) so not to make the application wait.
> 
> the notify function just takes arguments from **kwargs and just ignore *args, in kwargs you get the info passed as kwargs, for example icon, message text, etc. (see [this](https://github.com/TruncatedDinosour/arigram/blob/3f768ff00f26596ce60d7d86e7aa3e5dcfe35fb1/arigram/utils.py#L201) to see what gets passed) and converts them to string just in case something turns out to be `None` and them it just notifies the user using plyer and plays the [wav file](https://github.com/TruncatedDinosour/dotfiles-cleaned/raw/gentoo/dotfiles/config/arigram/resources/notification.wav) which is just the default telegram notification sound :)

i'm try to copied your configuration to put it in my configuration but i have this errors. I'm sorry because i am novice and i am not programmer:

![2021-12-07-100807_641x296_scrot](https://user-images.githubusercontent.com/88660859/145054434-c5180624-76db-4e27-9fdb-6d8bde9e6f4d.png)

And i downloaded the `notification.wav` from your dot files and i save it in `~ / .config / arigram / resources`, and sorry for my english.

**Comment by ar1ja** [comment]
> > Hi. sorry for taking a while to reply :)
> > In config you need to define `NOTIFY_FUNCTION` with a function that you want to be called on every notification, arguments will be passed to it as notification params :)
> > for example in my config I have:
> > ```python
> > from arigram import config as tg_config
> > from simpleaudio import WaveObject
> > from threading import Thread
> > from plyer import notification
> > 
> > 
> > class Custom:
> >     def _play_wav(self, wave_path: str) -> Thread:
> >         def player() -> None:
> >             wave_obj = WaveObject.from_wave_file(wave_path)
> >             play_obj = wave_obj.play()
> >             play_obj.wait_done()
> > 
> >         sound = Thread(target=player)
> >         sound.setDaemon(True)
> > 
> >         return sound
> > 
> >     def _notify(self, title: str, message: str) -> Thread:
> >         def notifier() -> None:
> >             if notification.notify is not None:
> >                 notification.notify(
> >                     app_name=f"arigram {arigram.__version__}",
> >                     title=title,
> >                     message=message,
> >                 )
> > 
> >         notif = Thread(target=notifier)
> >         notif.setDaemon(True)
> > 
> >         return notif
> > 
> >     def notify(self, *args, **kwargs) -> None:
> >         del args
> > 
> >         self._notify(str(kwargs.get("title")), str(kwargs.get("msg"))).start()
> >         self._play_wav(f"{tg_config.CONFIG_DIR}resources/notification.wav").start()
> > 
> > 
> > custom_code = Custom()
> > NOTIFY_FUNCTION = custom_code.notify
> > ```
> > 
> > 
> > the _... functions are just helpers, they self-expain i think, `_pay_wav()` just pays a wav file in a seperate thread and `_notify()` notifies you from a different thread and makes them daemonic (just makes them background) so not to make the application wait.
> > the notify function just takes arguments from **kwargs and just ignore *args, in kwargs you get the info passed as kwargs, for example icon, message text, etc. (see [this](https://github.com/TruncatedDinosour/arigram/blob/3f768ff00f26596ce60d7d86e7aa3e5dcfe35fb1/arigram/utils.py#L201) to see what gets passed) and converts them to string just in case something turns out to be `None` and them it just notifies the user using plyer and plays the [wav file](https://github.com/TruncatedDinosour/dotfiles-cleaned/raw/gentoo/dotfiles/config/arigram/resources/notification.wav) which is just the default telegram notification sound :)
> 
> i'm try to copied your configuration to put it in my configuration but i have this errors. I'm sorry because i am novice and i am not programmer:
> 
> ![2021-12-07-100807_641x296_scrot](https://user-images.githubusercontent.com/88660859/145054434-c5180624-76db-4e27-9fdb-6d8bde9e6f4d.png)
> 
> And i downloaded the `notification.wav` from your dot files and i save it in `~ / .config / arigram / resources`, and sorry for my english.

ya need to install simpleaudio and plyer :)

`python3 -m pip install --user simpleaudio plyer`

**Comment by d13g0x** [comment]
> > > Hi. sorry for taking a while to reply :)
> > > In config you need to define `NOTIFY_FUNCTION` with a function that you want to be called on every notification, arguments will be passed to it as notification params :)
> > > for example in my config I have:
> > > ```python
> > > from arigram import config as tg_config
> > > from simpleaudio import WaveObject
> > > from threading import Thread
> > > from plyer import notification
> > > 
> > > 
> > > class Custom:
> > >     def _play_wav(self, wave_path: str) -> Thread:
> > >         def player() -> None:
> > >             wave_obj = WaveObject.from_wave_file(wave_path)
> > >             play_obj = wave_obj.play()
> > >             play_obj.wait_done()
> > > 
> > >         sound = Thread(target=player)
> > >         sound.setDaemon(True)
> > > 
> > >         return sound
> > > 
> > >     def _notify(self, title: str, message: str) -> Thread:
> > >         def notifier() -> None:
> > >             if notification.notify is not None:
> > >                 notification.notify(
> > >                     app_name=f"arigram {arigram.__version__}",
> > >                     title=title,
> > >                     message=message,
> > >                 )
> > > 
> > >         notif = Thread(target=notifier)
> > >         notif.setDaemon(True)
> > > 
> > >         return notif
> > > 
> > >     def notify(self, *args, **kwargs) -> None:
> > >         del args
> > > 
> > >         self._notify(str(kwargs.get("title")), str(kwargs.get("msg"))).start()
> > >         self._play_wav(f"{tg_config.CONFIG_DIR}resources/notification.wav").start()
> > > 
> > > 
> > > custom_code = Custom()
> > > NOTIFY_FUNCTION = custom_code.notify
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > the _... functions are just helpers, they self-expain i think, `_pay_wav()` just pays a wav file in a seperate thread and `_notify()` notifies you from a different thread and makes them daemonic (just makes them background) so not to make the application wait.
> > > the notify function just takes arguments from **kwargs and just ignore *args, in kwargs you get the info passed as kwargs, for example icon, message text, etc. (see [this](https://github.com/TruncatedDinosour/arigram/blob/3f768ff00f26596ce60d7d86e7aa3e5dcfe35fb1/arigram/utils.py#L201) to see what gets passed) and converts them to string just in case something turns out to be `None` and them it just notifies the user using plyer and plays the [wav file](https://github.com/TruncatedDinosour/dotfiles-cleaned/raw/gentoo/dotfiles/config/arigram/resources/notification.wav) which is just the default telegram notification sound :)
> > 
> > 
> > i'm try to copied your configuration to put it in my configuration but i have this errors. I'm sorry because i am novice and i am not programmer:
> > ![2021-12-07-100807_641x296_scrot](https://user-images.githubusercontent.com/88660859/145054434-c5180624-76db-4e27-9fdb-6d8bde9e6f4d.png)
> > And i downloaded the `notification.wav` from your dot files and i save it in `~ / .config / arigram / resources`, and sorry for my english.
> 
> ya need to install simpleaudio and plyer :)
> 
> `python3 -m pip install --user simpleaudio plyer`

Thank you, i installed simpleaudio and plyer and works. Now i have another question... in your configuration works the daemon notification?

**Comment by ar1ja** [comment]
> 

Confused what you mean, but yes, my notifications work

**Comment by d13g0x** [comment]
> > 
> 
> Confused what you mean, but yes, my notifications work

haha i'm sorry i mean this one: 
![2021-12-08-134350_659x219_scrot](https://user-images.githubusercontent.com/88660859/145265738-578ebbeb-88a4-4df2-af18-f88da7aec20c.png)

My English is not very good, what I mean is that when someone writes me in Telegram I hear the sound but I do not see the floating message on my screen.

**Comment by ar1ja** [comment]
> > Confused what you mean, but yes, my notifications work
> 
> haha i'm sorry i mean this one: ![2021-12-08-134350_659x219_scrot](https://user-images.githubusercontent.com/88660859/145265738-578ebbeb-88a4-4df2-af18-f88da7aec20c.png)
> 
> My English is not very good, what I mean is that when someone writes me in Telegram I hear the sound but I do not see the floating message on my screen.

This is very nice, but weird, maybe we should try not starting in a new thread, any plyer errors? maybe you're on wayland too heh, you can try also using the os module :)

without threading (on the notification part):

```py
from arigram import config as tg_config
from simpleaudio import WaveObject
from threading import Thread
from plyer import notification


class Custom:
    def _play_wav(self, wave_path: str) -> Thread:
        def player() -> None:
            wave_obj = WaveObject.from_wave_file(wave_path)
            play_obj = wave_obj.play()
            play_obj.wait_done()

        sound = Thread(target=player)
        sound.setDaemon(True)

        return sound

    def _notify(self, title: str, message: str) -> None:
        if notification.notify is not None:
            notification.notify(
                app_name=f"arigram {arigram.__version__}",
                title=title,
                message=message,
            )

    def notify(self, *args, **kwargs) -> None:
        del args

        self._notify(str(kwargs.get("title")), str(kwargs.get("msg")))
        self._play_wav(f"{tg_config.CONFIG_DIR}resources/notification.wav").start()


custom_code = Custom()
NOTIFY_FUNCTION = custom_code.notify
```


using os module (using notify-send, you can change it up):

```py
import os
import arigram

def notify(**kwargs) -> None:
    os.system(f"notify-send \"{kwargs.get('title')}\" \"{kwargs.get({kwargs.get('msg')}\")


NOTIFY_FUNCTION = notify
```

might also be that plyer does not support your thing, as it's dynamic, so maybe os method will work. os.system just executes a command
