### ISSUE TITLE
[Question] Is there a way to use Arrow keys?

### ISSUE THREAD

**Issue by linuxmobile** [TruncatedDinosour/arigram#7]
Is there a way to use Arrow keys instead of `h, j, k, l` ?

**Comment by ar1ja** [comment]
Yep, I recently removed it in [this commit](https://github.com/TruncatedDinosour/arigram/commit/9bfc08f357616dd777aa4b0665526cfe75fa0fc5) (arigram/controllers.py to be specific), if you want you can bring it back in `CUSTOM_KEYBINDS`, but I am not planning on bringing arrow keys back :)

**Comment by linuxmobile** [comment]
> Yep, I recently removed it in [this commit](https://github.com/TruncatedDinosour/arigram/commit/9bfc08f357616dd777aa4b0665526cfe75fa0fc5) (arigram/controllers.py to be specific), if you want you can bring it back in `CUSTOM_KEYBINDS`, but I am not planning on bringing arrow keys back :)

Great!!! Thx u!
